TELANGANA_MARKETS = [
    {"name": "Enumamula (Warangal)", "name_telugu": "ఎనుమాముల", "district": "Hanumakonda", "latitude": 17.9784, "longitude": 79.5941, "market_type": "APMC", "market_fee_percent": 1.0},
    {"name": "Bowenpally (Hyderabad)", "name_telugu": "బోయెన్పల్లి", "district": "Hyderabad", "latitude": 17.4718, "longitude": 78.4749, "market_type": "APMC", "market_fee_percent": 1.0},
    {"name": "Nizamabad", "name_telugu": "నిజామాబాద్", "district": "Nizamabad", "latitude": 18.6725, "longitude": 78.0940, "market_type": "APMC", "market_fee_percent": 1.0},
    {"name": "Khammam", "name_telugu": "ఖమ్మం", "district": "Khammam", "latitude": 17.2473, "longitude": 80.1514, "market_type": "APMC", "market_fee_percent": 1.0},
    {"name": "Suryapet", "name_telugu": "సూర్యాపేట", "district": "Suryapet", "latitude": 17.1399, "longitude": 79.6237, "market_type": "APMC", "market_fee_percent": 1.0},
    {"name": "Miryalaguda", "name_telugu": "మిర్యాలగూడ", "district": "Nalgonda", "latitude": 16.8735, "longitude": 79.5618, "market_type": "APMC", "market_fee_percent": 1.0},
    {"name": "Karimnagar", "name_telugu": "కరీంనగర్", "district": "Karimnagar", "latitude": 18.4386, "longitude": 79.1288, "market_type": "APMC", "market_fee_percent": 1.0},
    {"name": "Adilabad", "name_telugu": "ఆదిలాబాద్", "district": "Adilabad", "latitude": 19.6641, "longitude": 78.5320, "market_type": "APMC", "market_fee_percent": 1.0},
    {"name": "Jadcherla (Mahabubnagar)", "name_telugu": "జడ్చర్ల", "district": "Mahabubnagar", "latitude": 16.7630, "longitude": 78.1380, "market_type": "APMC", "market_fee_percent": 1.0},
    {"name": "Jammikunta", "name_telugu": "జమ్మికుంట", "district": "Karimnagar", "latitude": 18.2884, "longitude": 79.5218, "market_type": "APMC", "market_fee_percent": 1.0},
    {"name": "Siddipet", "name_telugu": "సిద్దిపేట", "district": "Siddipet", "latitude": 18.1019, "longitude": 78.8520, "market_type": "APMC", "market_fee_percent": 1.0},
    {"name": "Gadwal", "name_telugu": "గద్వాల్", "district": "Jogulamba Gadwal", "latitude": 16.2336, "longitude": 77.8044, "market_type": "APMC", "market_fee_percent": 1.0},
    {"name": "Nalgonda", "name_telugu": "నల్గొండ", "district": "Nalgonda", "latitude": 17.0500, "longitude": 79.2667, "market_type": "APMC", "market_fee_percent": 1.0},
    {"name": "Jagtial", "name_telugu": "జగిత్యాల", "district": "Jagtial", "latitude": 18.7946, "longitude": 78.9137, "market_type": "APMC", "market_fee_percent": 1.0},
    {"name": "Zaheerabad", "name_telugu": "జహీరాబాద్", "district": "Sangareddy", "latitude": 17.6812, "longitude": 77.6074, "market_type": "APMC", "market_fee_percent": 1.0},
    {"name": "Mancherial", "name_telugu": "మంచిర్యాల", "district": "Mancherial", "latitude": 18.8685, "longitude": 79.4427, "market_type": "APMC", "market_fee_percent": 1.0},
    {"name": "Malakpet (Hyderabad)", "name_telugu": "మలక్పేట", "district": "Hyderabad", "latitude": 17.3780, "longitude": 78.4982, "market_type": "APMC", "market_fee_percent": 1.0},
    {"name": "Batasingaram (Rangareddy)", "name_telugu": "బాటసింగారం", "district": "Rangareddy", "latitude": 17.3357, "longitude": 78.5872, "market_type": "APMC", "market_fee_percent": 1.0},
    {"name": "Sultanabad (Peddapalli)", "name_telugu": "సుల్తానాబాద్", "district": "Peddapalli", "latitude": 18.6175, "longitude": 79.3731, "market_type": "APMC", "market_fee_percent": 1.0},
    {"name": "Gajwel", "name_telugu": "గజ్వేల్", "district": "Siddipet", "latitude": 17.8510, "longitude": 78.6873, "market_type": "APMC", "market_fee_percent": 1.0},
]
